[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js API routes are handled automatically by @netlify/plugin-nextjs
# Remove manual redirects that might interfere

# Handle SPA routing (exclude API and static files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Default catch-all for client-side routing (but not API routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  # MongoDB connection timeout
  "___netlify-handler" = { timeout = 30 }

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# API-specific headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"